#!/usr/bin/env python3
"""Emit C for the functions of one funcs.toml module.

Output: <out>/<module>.c and <out>/<module>.h. One C function per
(routine, entry state), one labelled block per instruction.
Unimplemented (opcode, width) combinations are fatal.
"""
from __future__ import annotations

import argparse
import os
import sys

import decode
import funcs
from decode import DecodeError, Insn

HEADER = '/* generated by recomp/emit.py from funcs.toml; do not edit */'


class EmitError(Exception):
    pass


def _dp(i: Insn) -> str:
    return f'0x{i.operand:02X}'


def _abs(i: Insn) -> str:
    return f'0x{i.operand:04X}'


def _long(i: Insn) -> str:
    return f'0x{i.operand:06X}'


def _imm(i: Insn) -> str:
    return f'0x{i.operand:0{2 if i.size == 2 else 4}X}'


def _at(i: Insn) -> str:
    return f'0x{i.addr:06X}'


def _branch(cond: str):
    def f(i: Insn) -> list[str]:
        tgt = f'goto L_{i.branch_target():06X};'
        return [tgt] if not cond else [f'if ({cond}) {tgt}']
    return f


# ---- template generation ----
# (opcode, width) -> body lines. width: '8'/'16' for M/X-sized ops, '' otherwise.

# mode -> (effective-address expression, 16-bit access wraps in bank 0)
_EA = {
    'dp':            (lambda i: f'ea_dp(cpu, {_dp(i)})', True),
    'dp_x':          (lambda i: f'ea_dp_x(cpu, {_dp(i)})', True),
    'dp_y':          (lambda i: f'ea_dp_y(cpu, {_dp(i)})', True),
    'sr':            (lambda i: f'ea_sr(cpu, {_dp(i)})', True),
    'abs':           (lambda i: f'ea_abs(cpu, {_abs(i)})', False),
    'abs_x':         (lambda i: f'ea_abs_x(cpu, {_abs(i)})', False),
    'abs_y':         (lambda i: f'ea_abs_y(cpu, {_abs(i)})', False),
    'long':          (lambda i: _long(i), False),
    'long_x':        (lambda i: f'ea_long_x(cpu, {_long(i)})', False),
    'dp_ind':        (lambda i: f'ea_dp_ind(cpu, {_dp(i)})', False),
    'dp_x_ind':      (lambda i: f'ea_dp_x_ind(cpu, {_dp(i)})', False),
    'dp_ind_y':      (lambda i: f'ea_dp_ind_y(cpu, {_dp(i)})', False),
    'dp_ind_long':   (lambda i: f'ea_dp_ind_long(cpu, {_dp(i)})', False),
    'dp_ind_long_y': (lambda i: f'ea_dp_ind_long_y(cpu, {_dp(i)})', False),
    'sr_ind_y':      (lambda i: f'ea_sr_ind_y(cpu, {_dp(i)})', False),
}


def _rd(expr: str, w: str, b0: bool) -> str:
    if w == '8':
        return f'read8({expr})'
    return f'read16_b0({expr})' if b0 else f'read16({expr})'


def _wr(expr: str, w: str, b0: bool, val: str) -> str:
    if w == '8':
        return f'write8({expr}, {val});'
    return f'write16_b0({expr}, {val});' if b0 else f'write16({expr}, {val});'


def _reg(name: str, w: str) -> str:
    """Register value at width w."""
    if name == 'A':
        return 'a8(cpu)' if w == '8' else 'cpu->A'
    return f'(uint8_t)cpu->{name}' if w == '8' else f'cpu->{name}'


def _value(i: Insn, w: str) -> str:
    if i.mode in ('imm_m', 'imm_x'):
        return _imm(i)
    ea, b0 = _EA[i.mode]
    return _rd(ea(i), w, b0)


_LOADS = {'LDA': 'lda', 'LDX': 'ldx', 'LDY': 'ldy', 'ORA': 'ora', 'AND': 'and', 'EOR': 'eor'}
_STORES = {'STA': 'cpu->A', 'STX': 'cpu->X', 'STY': 'cpu->Y', 'STZ': '0'}
_RMW = {'INC': 'inc', 'DEC': 'dec', 'ASL': 'asl', 'LSR': 'lsr', 'ROL': 'rol', 'ROR': 'ror',
        'TSB': 'tsb', 'TRB': 'trb'}
_FLAGS = {'CLC': 'cpu->c = 0;', 'SEC': 'cpu->c = 1;', 'CLI': 'cpu->i = 0;', 'SEI': 'cpu->i = 1;',
          'CLD': 'cpu->d = 0;', 'SED': 'cpu->d = 1;', 'CLV': 'cpu->v = 0;'}
_BRANCH = {'BPL': '!cpu->n', 'BMI': 'cpu->n', 'BVC': '!cpu->v', 'BVS': 'cpu->v',
           'BCC': '!cpu->c', 'BCS': 'cpu->c', 'BNE': '!cpu->z', 'BEQ': 'cpu->z',
           'BRA': '', 'BRL': ''}
# transfer -> (dest register, source expression at 16 bits, width source)
_XFER = {'TAX': ('X', 'cpu->A'), 'TAY': ('Y', 'cpu->A'), 'TXA': ('A', 'cpu->X'),
         'TYA': ('A', 'cpu->Y'), 'TXY': ('Y', 'cpu->X'), 'TYX': ('X', 'cpu->Y'),
         'TSX': ('X', 'cpu->S')}


def _set_reg(name: str, w: str, val16: str) -> list[str]:
    if name == 'A':
        if w == '8':
            return [f'set_a8(cpu, (uint8_t){val16});', 'set_nz8(cpu, a8(cpu));']
        return [f'cpu->A = {val16};', 'set_nz16(cpu, cpu->A);']
    if w == '8':
        return [f'cpu->{name} = (uint8_t){val16};', f'set_nz8(cpu, (uint8_t)cpu->{name});']
    return [f'cpu->{name} = {val16};', f'set_nz16(cpu, cpu->{name});']


def _generate(mn: str, md: str, w: str):
    """Template for one (mnemonic, mode, width), or None."""
    if mn in _LOADS and (md in _EA or md in ('imm_m', 'imm_x')):
        return lambda i: [f'{_LOADS[mn]}{w}(cpu, {_value(i, w)});']
    if mn in ('ADC', 'SBC') and (md in _EA or md == 'imm_m'):
        return lambda i: [f'{mn.lower()}{w}(cpu, {_value(i, w)}, {_at(i)});']
    if mn in ('CMP', 'CPX', 'CPY') and (md in _EA or md in ('imm_m', 'imm_x')):
        reg = {'CMP': 'A', 'CPX': 'X', 'CPY': 'Y'}[mn]
        return lambda i: [f'cmp{w}(cpu, {_reg(reg, w)}, {_value(i, w)});']
    if mn == 'BIT' and (md in _EA or md == 'imm_m'):
        return lambda i: [f'bit{w}(cpu, {_value(i, w)}, {int(md == "imm_m")});']
    if mn in _STORES and md in _EA:
        ea, b0 = _EA[md]
        src = _STORES[mn]
        val = src if src == '0' else _reg(src[5:], w)
        return lambda i: [_wr(ea(i), w, b0, val)]
    if mn in _RMW and md in _EA:
        ea, b0 = _EA[md]
        return lambda i: [f'uint32_t ea = {ea(i)};',
                          _wr('ea', w, b0, f'{_RMW[mn]}{w}(cpu, {_rd("ea", w, b0)})')]
    if mn in _RMW and md == 'A':
        if w == '8':
            return lambda i: [f'set_a8(cpu, {_RMW[mn]}8(cpu, a8(cpu)));']
        return lambda i: [f'cpu->A = {_RMW[mn]}16(cpu, cpu->A);']
    if mn in _FLAGS:
        return lambda i: [_FLAGS[mn]]
    if mn in _BRANCH:
        return _branch(_BRANCH[mn])
    if mn in _XFER:
        dst, src = _XFER[mn]
        return lambda i: _set_reg(dst, w, src)
    if mn in ('INX', 'INY', 'DEX', 'DEY'):
        reg = mn[2]
        op = '+' if mn.startswith('IN') else '-'
        return lambda i: _set_reg(reg, w, f'(uint16_t)(cpu->{reg} {op} 1)')
    if mn in ('PHA', 'PHX', 'PHY'):
        reg = mn[2]
        if w == '8':
            return lambda i: [f'push8(cpu, (uint8_t)cpu->{reg});']
        return lambda i: [f'push16(cpu, cpu->{reg});']
    if mn in ('PLA', 'PLX', 'PLY'):
        reg = mn[2]
        return lambda i: _set_reg(reg, w, 'pull8(cpu)' if w == '8' else 'pull16(cpu)')
    return None


_SPECIAL = {
    (0x08, ''):   lambda i: ['push8(cpu, get_p(cpu));'],                                   # PHP
    (0x28, ''):   lambda i: ['set_p(cpu, pull8(cpu));'],                                   # PLP
    (0x60, ''):   lambda i: ['op_rts(cpu);', 'return;'],                                   # RTS
    (0x7B, ''):   lambda i: ['op_tdc(cpu);'],                                              # TDC
    (0x5B, ''):   lambda i: ['cpu->DP = cpu->A;', 'set_nz16(cpu, cpu->DP);'],              # TCD
    (0x1B, ''):   lambda i: ['cpu->S = cpu->A;'],                                          # TCS
    (0x3B, ''):   lambda i: ['cpu->A = cpu->S;', 'set_nz16(cpu, cpu->A);'],                # TSC
    (0x9A, ''):   lambda i: ['cpu->S = cpu->X;'],                                          # TXS
    (0xEB, ''):   lambda i: ['cpu->A = (uint16_t)(cpu->A >> 8 | cpu->A << 8);',            # XBA
                             'set_nz8(cpu, a8(cpu));'],
    (0x8B, ''):   lambda i: ['push8(cpu, cpu->DB);'],                                      # PHB
    (0xAB, ''):   lambda i: ['cpu->DB = pull8(cpu);', 'set_nz8(cpu, cpu->DB);'],           # PLB
    (0x0B, ''):   lambda i: ['push16(cpu, cpu->DP);'],                                     # PHD
    (0x2B, ''):   lambda i: ['cpu->DP = pull16(cpu);', 'set_nz16(cpu, cpu->DP);'],         # PLD
    (0x4B, ''):   lambda i: [f'push8(cpu, 0x{i.addr >> 16:02X});'],                        # PHK
    (0xF4, ''):   lambda i: [f'push16(cpu, {_abs(i)});'],                                  # PEA
    (0xD4, ''):   lambda i: [f'push16(cpu, read16_b0(ea_dp(cpu, {_dp(i)})));'],            # PEI
    (0x62, ''):   lambda i: [f'push16(cpu, 0x{i.branch_target() & 0xFFFF:04X});'],        # PER
    (0xC2, ''):   lambda i: [f'op_rep(cpu, 0x{i.operand:02X});'],                          # REP
    (0xE2, ''):   lambda i: [f'op_sep(cpu, 0x{i.operand:02X});'],                          # SEP
    (0xEA, ''):   lambda i: [';'],                                                         # NOP
    (0x54, '16'): lambda i: [f'mvn16(cpu, 0x{i.operand & 0xFF:02X}, 0x{i.operand >> 8:02X});'],  # MVN
}


def _build_templates() -> dict:
    out = dict(_SPECIAL)
    special_ops = {op for op, _ in _SPECIAL}
    for op, (mn, md) in decode.OPCODES.items():
        if op in special_ops:
            continue
        dep = decode.width_dependency(mn, md)
        for w in (['8', '16'] if dep else ['']):
            f = _generate(mn, md, w)
            if f is not None:
                out[(op, w)] = f
    return out


TEMPLATES = _build_templates()

NO_FALLTHROUGH = {'RTS', 'RTL', 'RTI', 'BRA', 'BRL', 'JMP', 'JML', 'STP'}


def implemented_opcodes() -> set[int]:
    return {op for op, _ in TEMPLATES} | {0x20, 0x4C}   # JSR/JMP abs: emit_function


def c_name(addr: int, st: decode.State) -> str:
    return f'f_{addr:06X}_{st.tag()}'


def emit_function(fm: funcs.FuncMeta, fn: decode.Function) -> list[str]:
    st = fn.state
    lines = [
        f'/* ${fm.addr:06X} {fm.name}: {fn.size} bytes, entry {st.tag()} e{int(st.e)} */',
        f'void {c_name(fm.addr, st)}(CPU *cpu)',
        '{',
        f'    cpu_enter(cpu, 0x{fm.addr:06X}, {int(st.m)}, {int(st.x)});',
    ]
    if fn.insns[0].addr != fm.addr:
        raise EmitError(f'${fm.addr:06X}: entry is not the lowest decoded address')
    addrs = {i.addr for i in fn.insns}
    for k, i in enumerate(fn.insns):
        nxt = fn.insns[k + 1] if k + 1 < len(fn.insns) else None
        if i.mnemonic not in NO_FALLTHROUGH and (nxt is None or nxt.addr != i.next_addr):
            raise EmitError(f'${i.addr:06X}: fall-through to ${i.next_addr:06X} not contiguous')
        try:
            w = i.width()
        except DecodeError as ex:
            raise EmitError(str(ex)) from None
        t = TEMPLATES.get((i.opcode, w))
        if i.opcode == 0x20 and i.addr in fn.calls:
            target, cst = fn.calls[i.addr]
            ret = (i.addr + 2) & 0xFFFF
            t = lambda i: [f'push16(cpu, 0x{ret:04X});',
                           f'{c_name(target, cst)}(cpu);',
                           f'cpu_check_return(cpu, 0x{i.addr:06X}, 0x{(ret + 1) & 0xFFFF:04X});']
        if i.opcode == 0x4C:
            if i.addr in fn.tails:
                target, cst = fn.tails[i.addr]
                t = lambda i: [f'{c_name(target, cst)}(cpu);', 'return;']
            else:
                t = lambda i: [f'goto L_{(i.addr & 0xFF0000) | i.operand:06X};']
        if t is None:
            raise EmitError(f'${i.addr:06X}: {i.text()} (opcode ${i.opcode:02X}, '
                            f'width {w or "-"}) not implemented')
        tgt = i.branch_target()
        if i.opcode == 0x4C and i.addr not in fn.tails:
            tgt = (i.addr & 0xFF0000) | i.operand
        if tgt is not None and tgt not in addrs:
            raise EmitError(f'${i.addr:06X}: branch target ${tgt:06X} not in function')
        body = t(i)
        if i.mnemonic == 'PLP':
            if nxt is None or nxt.m is None or nxt.x is None:
                raise EmitError(f'${i.addr:06X}: PLP restores unknown M/X')
            body.append(f'cpu_check_mx(cpu, 0x{i.addr:06X}, {int(nxt.m)}, {int(nxt.x)});')
        lines.append(f'L_{i.addr:06X}: /* {i.text()} */')
        if len(body) == 1:
            lines.append(f'    {{ {body[0]} }}')
        else:
            lines.append('    {')
            lines += [f'        {b}' for b in body]
            lines.append('    }')
    lines.append('}')
    return lines


def emit_module(reg: funcs.Registry, metas: list[funcs.FuncMeta], module: str) -> tuple[str, str]:
    sel = [fm for fm in metas if fm.module == module]
    if not sel:
        raise EmitError(f'no functions in module {module!r}')
    guard = f'CT_OUT_{module.upper()}_H'
    c = [HEADER, '#include "ops.h"', '#include "ct_funcs.h"', f'#include "{module}.h"', '']
    h = [HEADER, f'#ifndef {guard}', f'#define {guard}', '', '#include <stdint.h>', '',
         '#include "cpu.h"', '']
    table = []
    for fm in sel:
        for st in fm.entry_states():
            try:
                fn = reg.function(fm.addr, st)
            except DecodeError as ex:
                raise EmitError(f'{fm.name}: {ex}') from None
            c += emit_function(fm, fn) + ['']
            name = c_name(fm.addr, st)
            h.append(f'void {name}(CPU *cpu);  /* {fm.name} */')
            table.append(f'    {{"{fm.name}", 0x{fm.addr:06X}, "{st.tag()}", {fn.size}, {name}}},')
    h += ['', 'typedef struct {', '    const char *name;', '    uint32_t addr;',
          '    const char *state;', '    uint16_t size;', '    void (*fn)(CPU *);',
          f'}} ct_func_{module};', '',
          f'extern const ct_func_{module} {module}_funcs[];',
          f'extern const unsigned {module}_func_count;', '', '#endif', '']
    c += [f'const ct_func_{module} {module}_funcs[] = {{'] + table + ['};',
          f'const unsigned {module}_func_count = {len(table)};', '']
    return '\n'.join(c), '\n'.join(h)


def emit_prototypes(reg: funcs.Registry, metas: list[funcs.FuncMeta]) -> tuple[str, str]:
    """ct_funcs.h (all prototypes, table type) and ct_funcs.c (table)."""
    h = [HEADER, '#ifndef CT_OUT_FUNCS_H', '#define CT_OUT_FUNCS_H', '', '#include <stdint.h>', '',
         '#include "cpu.h"', '']
    c = [HEADER, '#include "ct_funcs.h"', '', 'const ct_func ct_funcs[] = {']
    n = 0
    for fm in metas:
        for st in fm.entry_states():
            name = c_name(fm.addr, st)
            fn = reg.function(fm.addr, st)
            h.append(f'void {name}(CPU *cpu);  /* {fm.name} */')
            db = fm.db if fm.db is not None else -1
            dp = fm.dp if fm.dp is not None else -1
            c.append(f'    {{"{fm.name}", 0x{fm.addr:06X}, {int(st.m)}, {int(st.x)}, {fn.size}, '
                     f'{db}, {dp}, {name}}},')
            n += 1
    h += ['', 'typedef struct {', '    const char *name;', '    uint32_t addr;',
          '    uint8_t m, x;', '    uint16_t size;',
          '    int db, dp;         /* entry DB/DP from funcs.toml, -1 if unknown */',
          '    void (*fn)(CPU *);', '} ct_func;', '',
          'extern const ct_func ct_funcs[];', 'extern const unsigned ct_func_count;', '',
          '#endif', '']
    c += ['};', f'const unsigned ct_func_count = {n};', '']
    return '\n'.join(h), '\n'.join(c)


def modules(metas: list[funcs.FuncMeta]) -> list[str]:
    return sorted({fm.module for fm in metas})


def write_if_changed(path: str, text: str) -> None:
    if os.path.isfile(path):
        with open(path) as f:
            if f.read() == text:
                return
    with open(path, 'w') as f:
        f.write(text)


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument('--module', help='emit one module (default: all)')
    ap.add_argument('--list-modules', action='store_true')
    ap.add_argument('--out', default=os.path.join(funcs.ROOT, 'out'))
    ap.add_argument('--rom')
    ap.add_argument('--funcs')
    a = ap.parse_args(argv)
    metas = funcs.load(a.funcs)
    if a.list_modules:
        print(';'.join(modules(metas)))
        return 0
    reg = funcs.Registry(decode.load_rom(a.rom), metas)
    os.makedirs(a.out, exist_ok=True)
    for mod in [a.module] if a.module else modules(metas):
        src, hdr = emit_module(reg, metas, mod)
        write_if_changed(os.path.join(a.out, f'{mod}.c'), src)
        write_if_changed(os.path.join(a.out, f'{mod}.h'), hdr)
    hdr, tab = emit_prototypes(reg, metas)
    write_if_changed(os.path.join(a.out, 'ct_funcs.h'), hdr)
    write_if_changed(os.path.join(a.out, 'ct_funcs.c'), tab)
    return 0


if __name__ == '__main__':
    try:
        sys.exit(main(sys.argv[1:]))
    except (DecodeError, EmitError) as ex:
        print(f'emit: {ex}', file=sys.stderr)
        sys.exit(1)
