#!/usr/bin/env python3
"""Emit C for the functions of one funcs.toml module.

Output: <out>/<module>.c and <out>/<module>.h. One C function per
(routine, entry state), one labelled block per instruction.
Unimplemented (opcode, width) combinations are fatal.
"""
from __future__ import annotations

import argparse
import os
import sys

import decode
import funcs
from decode import DecodeError, Insn

HEADER = '/* generated by recomp/emit.py from funcs.toml; do not edit */'


class EmitError(Exception):
    pass


def _dp(i: Insn) -> str:
    return f'0x{i.operand:02X}'


def _abs(i: Insn) -> str:
    return f'0x{i.operand:04X}'


def _long(i: Insn) -> str:
    return f'0x{i.operand:06X}'


# (opcode, width) -> body lines. width: '8'/'16' for M/X-sized ops, '' otherwise.
TEMPLATES = {
    (0x08, ''):   lambda i: ['push8(cpu, get_p(cpu));'],                                   # PHP
    (0x0A, '8'):  lambda i: ['asl_a8(cpu);'],                                              # ASL A
    (0x0A, '16'): lambda i: ['asl_a16(cpu);'],
    (0x28, ''):   lambda i: ['set_p(cpu, pull8(cpu));'],                                   # PLP
    (0x48, '8'):  lambda i: ['push8(cpu, a8(cpu));'],                                      # PHA
    (0x4A, '8'):  lambda i: ['lsr_a8(cpu);'],                                              # LSR A
    (0x4A, '16'): lambda i: ['lsr_a16(cpu);'],
    (0x60, ''):   lambda i: ['op_rts(cpu);', 'return;'],                                   # RTS
    (0x64, '8'):  lambda i: [f'write8(ea_dp(cpu, {_dp(i)}), 0);'],                         # STZ dp
    (0x6D, '16'): lambda i: [f'adc16(cpu, read16(ea_abs(cpu, {_abs(i)})), 0x{i.addr:06X});'],  # ADC abs
    (0x7B, ''):   lambda i: ['op_tdc(cpu);'],                                              # TDC
    (0x85, '8'):  lambda i: [f'write8(ea_dp(cpu, {_dp(i)}), a8(cpu));'],                   # STA dp
    (0x85, '16'): lambda i: [f'write16_dp(cpu, {_dp(i)}, cpu->A);'],
    (0x86, '16'): lambda i: [f'write16_dp(cpu, {_dp(i)}, cpu->X);'],                       # STX dp
    (0x8B, ''):   lambda i: ['push8(cpu, cpu->DB);'],                                      # PHB
    (0x8D, '8'):  lambda i: [f'write8(ea_abs(cpu, {_abs(i)}), a8(cpu));'],                 # STA abs
    (0x8F, '8'):  lambda i: [f'write8({_long(i)}, a8(cpu));'],                             # STA long
    (0x9C, '8'):  lambda i: [f'write8(ea_abs(cpu, {_abs(i)}), 0);'],                       # STZ abs
    (0xA5, '8'):  lambda i: [f'lda8(cpu, read8(ea_dp(cpu, {_dp(i)})));'],                  # LDA dp
    (0xA5, '16'): lambda i: [f'lda16(cpu, read16_dp(cpu, {_dp(i)}));'],
    (0xAB, ''):   lambda i: ['cpu->DB = pull8(cpu);', 'set_nz8(cpu, cpu->DB);'],           # PLB
    (0xAE, '16'): lambda i: [f'ldx16(cpu, read16(ea_abs(cpu, {_abs(i)})));'],              # LDX abs
    (0xAF, '16'): lambda i: [f'lda16(cpu, read16({_long(i)}));'],                          # LDA long
    (0xC2, ''):   lambda i: [f'op_rep(cpu, 0x{i.operand:02X});'],                          # REP
    (0xE2, ''):   lambda i: [f'op_sep(cpu, 0x{i.operand:02X});'],                          # SEP
    (0xEA, ''):   lambda i: [';'],                                                         # NOP
    (0xEE, '8'):  lambda i: [f'uint32_t ea = ea_abs(cpu, {_abs(i)});',                     # INC abs
                             'write8(ea, inc8(cpu, read8(ea)));'],
}

NO_FALLTHROUGH = {'RTS', 'RTL', 'RTI', 'BRA', 'BRL', 'JMP', 'JML', 'STP'}


def implemented_opcodes() -> set[int]:
    return {op for op, _ in TEMPLATES}


def c_name(addr: int, st: decode.State) -> str:
    return f'f_{addr:06X}_{st.tag()}'


def emit_function(fm: funcs.FuncMeta, fn: decode.Function) -> list[str]:
    st = fn.state
    lines = [
        f'/* ${fm.addr:06X} {fm.name}: {fn.size} bytes, entry {st.tag()} e{int(st.e)} */',
        f'void {c_name(fm.addr, st)}(CPU *cpu)',
        '{',
        f'    cpu_enter(cpu, 0x{fm.addr:06X}, {int(st.m)}, {int(st.x)});',
    ]
    if fn.insns[0].addr != fm.addr:
        raise EmitError(f'${fm.addr:06X}: entry is not the lowest decoded address')
    for k, i in enumerate(fn.insns):
        nxt = fn.insns[k + 1] if k + 1 < len(fn.insns) else None
        if i.mnemonic not in NO_FALLTHROUGH and (nxt is None or nxt.addr != i.next_addr):
            raise EmitError(f'${i.addr:06X}: fall-through to ${i.next_addr:06X} not contiguous')
        try:
            w = i.width()
        except DecodeError as ex:
            raise EmitError(str(ex)) from None
        t = TEMPLATES.get((i.opcode, w))
        if t is None:
            raise EmitError(f'${i.addr:06X}: {i.text()} (opcode ${i.opcode:02X}, '
                            f'width {w or "-"}) not implemented')
        body = t(i)
        if i.mnemonic == 'PLP':
            if nxt is None or nxt.m is None or nxt.x is None:
                raise EmitError(f'${i.addr:06X}: PLP restores unknown M/X')
            body.append(f'cpu_check_mx(cpu, 0x{i.addr:06X}, {int(nxt.m)}, {int(nxt.x)});')
        lines.append(f'L_{i.addr:06X}: /* {i.text()} */')
        if len(body) == 1:
            lines.append(f'    {{ {body[0]} }}')
        else:
            lines.append('    {')
            lines += [f'        {b}' for b in body]
            lines.append('    }')
    lines.append('}')
    return lines


def emit_module(rom: bytes, metas: list[funcs.FuncMeta], module: str) -> tuple[str, str]:
    sel = [fm for fm in metas if fm.module == module]
    if not sel:
        raise EmitError(f'no functions in module {module!r}')
    guard = f'CT_OUT_{module.upper()}_H'
    c = [HEADER, '#include "ops.h"', f'#include "{module}.h"', '']
    h = [HEADER, f'#ifndef {guard}', f'#define {guard}', '', '#include <stdint.h>', '',
         '#include "cpu.h"', '']
    table = []
    for fm in sel:
        for st in fm.entry_states():
            try:
                fn = decode.decode_function(rom, fm.addr, st)
            except DecodeError as ex:
                raise EmitError(f'{fm.name}: {ex}') from None
            c += emit_function(fm, fn) + ['']
            name = c_name(fm.addr, st)
            h.append(f'void {name}(CPU *cpu);  /* {fm.name} */')
            table.append(f'    {{"{fm.name}", 0x{fm.addr:06X}, "{st.tag()}", {fn.size}, {name}}},')
    h += ['', 'typedef struct {', '    const char *name;', '    uint32_t addr;',
          '    const char *state;', '    uint16_t size;', '    void (*fn)(CPU *);',
          f'}} ct_func_{module};', '',
          f'extern const ct_func_{module} {module}_funcs[];',
          f'extern const unsigned {module}_func_count;', '', '#endif', '']
    c += [f'const ct_func_{module} {module}_funcs[] = {{'] + table + ['};',
          f'const unsigned {module}_func_count = {len(table)};', '']
    return '\n'.join(c), '\n'.join(h)


def write_if_changed(path: str, text: str) -> None:
    if os.path.isfile(path):
        with open(path) as f:
            if f.read() == text:
                return
    with open(path, 'w') as f:
        f.write(text)


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument('--module', required=True)
    ap.add_argument('--out', default=os.path.join(funcs.ROOT, 'out'))
    ap.add_argument('--rom')
    ap.add_argument('--funcs')
    a = ap.parse_args(argv)
    rom = decode.load_rom(a.rom)
    src, hdr = emit_module(rom, funcs.load(a.funcs), a.module)
    os.makedirs(a.out, exist_ok=True)
    write_if_changed(os.path.join(a.out, f'{a.module}.c'), src)
    write_if_changed(os.path.join(a.out, f'{a.module}.h'), hdr)
    return 0


if __name__ == '__main__':
    try:
        sys.exit(main(sys.argv[1:]))
    except (DecodeError, EmitError) as ex:
        print(f'emit: {ex}', file=sys.stderr)
        sys.exit(1)
